# Generated by Django 4.2.6 on 2023-10-27 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "positions_cross",
                    models.JSONField(
                        default={"A": [], "B": [], "C": []},
                        verbose_name="Positions played by cross",
                    ),
                ),
                (
                    "positions_circle",
                    models.JSONField(
                        default={"A": [], "B": [], "C": []},
                        verbose_name="Positions played by circle",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Unfinished"),
                            (2, "Cross Victory"),
                            (3, "Circle Victory"),
                            (4, "Draw"),
                        ],
                        default=1,
                        verbose_name="Game Status",
                    ),
                ),
                (
                    "player_circle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circle",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Player Circle",
                    ),
                ),
                (
                    "player_cross",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cross",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Player Cross",
                    ),
                ),
            ],
        ),
    ]
