# Generated by Django 4.2.6 on 2023-10-27 15:04

import board.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_board_options_nodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='positions_circle',
            field=models.JSONField(default=board.constants.get_default_positions, verbose_name='Positions played by circle'),
        ),
        migrations.AlterField(
            model_name='board',
            name='positions_cross',
            field=models.JSONField(default=board.constants.get_default_positions, verbose_name='Positions played by cross'),
        ),
    ]
