# Generated by Django 4.2.6 on 2023-10-28 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0003_alter_board_positions_circle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nodes",
            name="board",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="board.board"
            ),
        ),
    ]
